package controllers

import io.github.casuallyblue.cucm.*
import play.libs.Json
import play.mvc.*
import javax.xml.ws.BindingProvider

/**
 * Main Controller for CUCM Rest service
 */
class CUCMRestController: Controller() {
    /**
     * AXL Client (generated by wsimport)
     */
    private val client: AXLPort = getClient()

    private fun getClient(): AXLPort {
        val service = AXLAPIService()
        val client = service.axlPort
        (client as BindingProvider).requestContext.let {
            it[BindingProvider.ENDPOINT_ADDRESS_PROPERTY] = "https://cdacucmpub.coramdeo.local:8443/axl/"
            it[BindingProvider.USERNAME_PROPERTY] = "cdaadmin"
            it[BindingProvider.PASSWORD_PROPERTY] = "cdaadmpw"
        }

        return client
    }

    /**
     * Get Json of all phones configured on the CUCM system
     */
    fun getPhones(): Result? {
        return ok(Json.newObject().putPOJO("phones", Json.toJson(getPhoneList())))
    }

    private fun getPhoneList(): List<LPhone> {
        val request = ListPhoneReq().let { req ->
            req.searchCriteria = ListPhoneReq.SearchCriteria().let { sc ->
                sc.name = "%"
                sc
            }
            req
        }
        return client.listPhone(request).`return`.phone
    }

    /**
     * Test of kotlin view template
     */
    fun testView(): Result {
        return views.TestView().render()
    }
}